server:
  port: 8088

spring:
  application:
    name: users-service
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/moviesdb
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          users-service:
            issuer-uri: ${KEYCLOAK_URL:http://keycloak:8082/}realms/digitalmedia
        registration:
          users-service:
            provider: users-service
            client-id: microservicios
            client-secret: 8wiOxewH0BE6A95mj3KPa7ugmxuw3mf1
            scope: openid
            #authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8088/*'

dm:
  users-service:
    serverUrl: ${KEYCLOAK_URL:http://keycloak:8082/}
    realm: digitalmedia
    clientId: microservicios
    clientSecret: 8wiOxewH0BE6A95mj3KPa7ugmxuw3mf1

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true
management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

app:
  cors:
    allowed-origins: http://localhost:3000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    enabled: true

