server:
  port: 8086

spring:
  application:
    name: ms-bill
  security:
    oauth2:
      client:
        provider:
          ms-bills:
            issuer-uri: http://localhost:8082/realms/digitalmedia
            token-uri: http://localhost:8082/realms/digitalmedia/protocol/openid-connect/token
        registration:
          ms-bills:
            provider: ms-bills
            #authorization-grant-type: authorization_code
            client-id: microservicios
            client-secret: 8wiOxewH0BE6A95mj3KPa7ugmxuw3mf1
            #scope: openid
            authorization-grant-type: client_credentials
            redirect-uri: 'http://localhost:8086/*'
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

#eureka:
 # instance:
  #  hostname: localhost
  #  instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   # instance-id: 127.0.0.1:8086
  #client:
   # service-url:
    #  defaultZone: http://localhost:8761/eureka/
    #enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
